export const projects = [


{
  id: "wristly",
  name: "Wristly",
  desc: "Premium watch e-commerce app built with React.js and TailwindCSS.",
  longDesc: "A production-grade premium watch e-commerce application built with React, showcasing modern frontend practices, state management, and performance optimization.",
  tech: ["React.js", "JavaScript (ES6+)", "Redux", "TailwindCSS", "Vite", "React Router DOM", "Local Storage","Vite PWA","Lucid-react", "react-toastify","swiper-slider","Skeleton-loading", "Vercel"],
  features: [
    "Filter, Search, and Sort products (combined logic)",
    "Product detail page with image gallery",
    "Cart with quantity management",
    "Wishlist toggle (single action)",
    "Authentication (localStorage-based)",
    "Checkout flow with order confirmation",
    "Skeleton loading UI",
    "Theme Toggler",
    "Prop Types",
    "Error Boundary",
    "PWA support",
    "React Lazy + Suspense",
  ],
  appFlow: [
    { text: "Browse Products → Filter / Search / Sort" },
    { text: "↓ Add to Wishlist (saves across refresh)", arrow: true },
    { text: "Add to Cart → quantity selected" },
    { text: "↓ Proceed to Checkout", arrow: true },
    { text: "Not logged in → Login Wall → Login / Signup" },
    { text: "↓ Fill Delivery Address + Select Payment", arrow: true },
    { text: "placeOrder() → Cart Clears → Order Confirmed ✓" },
  ],
  routes: [
    { icon: "🏠", label: "Home" },
    { icon: "🔍", label: "Browse Products" },
    { icon: "🛍️", label: "Product Details" },
    { icon: "❤️", label: "Wishlist" },
    { icon: "🛒", label: "Cart" },
    { icon: "💳", label: "Checkout" },
    { icon: "✅", label: "Order Confirm" },
    { icon: "👤", label: "My Account" },
    { icon: "🔐", label: "Login / Signup" },
    { icon: "ℹ️", label: "About" },
    { icon: "❓", label: "FAQ" },
    { icon: "📞", label: "Contact" },
    { icon: "⚠️", label: "404 Page" },
  ],
  techStack: [
    { name: "React 18", desc: "Hooks, lazy, Suspense for code splitting" },
    { name: "Redux Toolkit", desc: "createSlice, createAsyncThunk, store.subscribe for persistence" },
    { name: "React Router v6", desc: "Client-side routing with protected routes" },
    { name: "TailwindCSS", desc: "Utility-first styling with custom CSS variables" },
    { name: "Vite", desc: "Fast build tool and dev server" },
    { name: "localStorage", desc: "Cart, wishlist and auth persistence across refresh" },
    { name: "lucide-react", desc: "Icons — Heart, Cart, User, Menu, Trash etc." },
    { name: "react-toastify", desc: "Toast notifications for user actions" },
    { name: "swiper", desc: "Hero slider and related products carousel" },
    { name: "react-loading-skeleton", desc: "Skeleton loading UI for better UX" },
    {name:"Vite PWA" , desc:"PWA installation"}
  ],
  highlights: [
    { label: "Dark Mode", desc: "CSS variables + .dark on <html>, persists via localStorage, no flash on load" },
    { label: "PWA Support", desc: "Installable on mobile and desktop, works offline via Service Worker" },
    { label: "Redux Architecture", desc: "Centralized state, no prop drilling, store.subscribe for localStorage sync" },
    { label: "Performance", desc: "React.lazy + Suspense, React.memo, useCallback, useMemo to minimize re-renders" },
    { label: "PropTypes", desc: "Runtime prop validation on all components, catches bugs during development" },
    { label: "Error Boundary", desc: "Prevents full app crash, shows fallback UI on component errors" },
    {label:"Sliders", desc:"swiper slider enhanced UI/UX"},
    {label:"Skeleton-Loading" , desc:"enhanced UI/UX"},
  
    { label: "Auth Flow", desc: "Signup / Login stored in localStorage, logout clears session only" },
    {label:"Localstorage" , desc:"data remains after refresh"},
    {label:"toast", desc:"Toast alerts using Toastify"},
      { label: "Responsive Design", desc: "320px to desktop, Tailwind + custom CSS, mobile-first layout" },
  ],
  errorFlows: [
    {
      title: "Invalid product ID",
      steps: [
        { text: "User visits /ProductDetails/999" },
        { text: "product = undefined", type: "trigger" },
        { text: "if (!product) check fires" },
        { text: "'Product not found' UI shown", type: "ok" },
      ],
    },
    {
      title: "Undefined specs crash",
      steps: [
        { text: "product.specs is undefined" },
        { text: "Object.entries(undefined)", type: "trigger" },
        { text: "Error Boundary catches it" },
        { text: "Fallback UI shown", type: "ok" },
      ],
    },
    {
      title: "Unknown route",
      steps: [
        { text: "User visits /randompage" },
        { text: "No matching route", type: "trigger" },
        { text: "Wildcard (*) catches it" },
        { text: "404 Page shown", type: "ok" },
      ],
    },
  ],
  github: "https://github.com/mayurpanchal-12/Wristly_React-Project",
  live: "https://wristy-react-project.vercel.app/",
  status: "Completed",
},
    {
      id: "Finance Tracker",
      name: "Advanced Finance Tracker",
      desc: " helps users manage Transactions , future transactions, analytics, and financial news",
      longDesc:"A full-featured Finance Tracker web application that helps users manage income, expenses, future transactions, analytics, and financial news — all in one place.The app supports voice-to-text input, search functionality , advanced filtering, interactive charts, and CSV/PDF exports with real-time balance updates.",
      tech: [
  "React",
  "Context API",
  "Tailwind CSS",
  "JavaScript (ES6+)",
  "Browser Speech API",
  "Chart library",
  "CSV / PDF export utilities",
  "Finance News API",
  "Localstorage"
],
      features: ["Transaction Management , Filter & Search , Download-Csv & PDF" , "Schedule Transactions " , "Charts & Analytics" , "Summary" , "notes" , "News"],
     
       appFlow: [
  { text: "Open App → View Transaction Tracker (Home)" },
  { text: "↓ Add / Edit / Delete Transactions", arrow: true },
  { text: "Set future-dated transaction → Scheduled Transactions table" },
  { text: "↓ On scheduled date → auto-moves to main Tracker", arrow: true },
  { text: "Filter by Month / Type / Category / Search" },
  { text: "↓ View filtered results in table + Summary", arrow: true },
  { text: "Download data → CSV or PDF via DownloadDropdown" },
  { text: "↓ View Charts → Line chart + Income/Expense pie charts", arrow: true },
  { text: "View Notes → all transactions with notes listed" },
  { text: "↓ View News → Finance headlines from Alpha Vantage API", arrow: true },
  { text: "News loader fails → NewsErrorPage shown ✓" },
],

routes: [
  { icon: "📋", label: "Tracker (Home)" },
  { icon: "➕", label: "Set Transaction" },
  { icon: "📊", label: "Charts" },
  { icon: "📝", label: "Notes" },
  { icon: "📰", label: "News" },
  { icon: "⚠️", label: "News Error" },
  { icon: "❓", label: "404 Wildcard" },
],

techStack: [
  { name: "React 18", desc: "Hooks, lazy, Suspense for code-split page loading" },
  { name: "React Router v6", desc: "createBrowserRouter, loader, errorElement, wildcard route" },
  { name: "Context API + useReducer", desc: "TransactionContext — centralized state, no prop drilling" },
  { name: "TailwindCSS v4", desc: "Utility-first styling with custom CSS variables and @layer" },
  { name: "Chart.js", desc: "Dynamic line + pie charts for income/expense analysis" },
  { name: "Alpha Vantage API", desc: "Live finance news fetched via route loader" },
  { name: "localStorage", desc: "Transactions, filters and balance persisted across refresh" },
  {name:"browser speech Api " , desc:"voice input"},
  { name: "Inter (Google Fonts)", desc: "Primary typeface across the entire UI" },
  { name: "Vite", desc: "Fast build tool with import.meta.env for API key" },
],

highlights: [
  { label: "Scheduled Transactions", desc: "Future-dated entries sit in a separate table and auto-promote to main tracker on their date" },
  { label: "Context + useReducer", desc: "Two reducers (transactions + filters) in one provider — clean dispatch pattern, no Redux needed" },
  { label: "Code Splitting", desc: "All pages are React.lazy with Suspense + PageLoader fallback — only loads what's needed" },
  { label: "Error Boundary", desc: "Wraps complex pages — prevents full app crash, shows fallback UI on render errors" },
    { label: "CSV + PDF Export", desc: "DownloadDropdown lets users export transaction data in two formats" },
      { label: "Charts", desc: "analytics with Overall balance - Line chart & Income- Expense with Pie chart" },
  { label: "Route-level Error Handling", desc: "News route uses errorElement: <NewsErrorPage /> for loader failures separate from ErrorBoundary" },
  {label:"Locatstorage" , desc:"Localstorage support"},
  { label: "Speech Input", desc: "useSpeechInput hook enables voice-to-text in the transaction form" },
  { label: "Responsive Design", desc: "Mobile-first layout using Tailwind, max-w-[1200px] centered root, flex-col gap structure" },
  { label: "Running Balance", desc: "Each filtered transaction gets a live-computed balance column via useMemo" },
],

errorFlows: [
  {
    title: "News API fails",
    steps: [
      { text: "User navigates to /news" },
      { text: "newsLoader() throws", type: "trigger" },
      { text: "React Router catches loader error" },
      { text: "errorElement: <NewsErrorPage /> shown", type: "ok" },
    ],
  },
  {
    title: "Page render crash",
    steps: [
      { text: "ChartPage / NotesPage / etc renders" },
      { text: "Unexpected JS error thrown", type: "trigger" },
      { text: "ErrorBoundary catches it" },
      { text: "Fallback UI + Try Again shown", type: "ok" },
    ],
  },
  {
    title: "Unknown route",
    steps: [
      { text: "User visits /randompage" },
      { text: "No matching route found", type: "trigger" },
      { text: "Wildcard (*) catches it" },
      { text: "404 Page shown", type: "ok" },
    ],
  },
  {
    title: "No transactions with notes",
    steps: [
      { text: "User opens /notes" },
      { text: "transactionsWithNotes.length === 0", type: "trigger" },
      { text: "Empty state check fires" },
      { text: "'No notes yet' message shown", type: "ok" },
    ],
  },
],
      github: "https://github.com/mayurpanchal-12/FinanceTracker_Reactjs.git",
      live: "https://finance-tracker-reactjs-sandy.vercel.app/",
      status: "Completed",
      
    },
    {
      id: "Advance Todo Manager",
      name: "Advanced Todo Manager",
      desc: "Advanced Todo app with task management, export options, with localStorage ",
      longDesc: "A feature-richapplication allows CRUD  with advanced options like priority, categories, file attachments, and deadlines. It includes filtering, search, status tracking, and export functionality (PDF/CSV), with persistent data storage using localStorage and a responsive, user-friendly interface.",
      tech: [
  "React 18",
  "Vite",
  "Context API",
  "JavaScript (ES6+)",
  "HTML & Tailwind CSS",
  "localStorage",
  "Vercel",
   "Web Speech API",
   "FileReader API ",
   "jsPDF",
  "GitHub"

],
      features: [
"CRUD",
"Set Priority & Category",
  "Toggle Status",
  "Filters",
  "Persistent Storage",
  "Counts & Clear All",
  "Export Options",
  "Search Functionality",
  "Attach PDF , image",
  "Voice input"
],
appFlow: [
  { text: "Open App → View all Todos grouped by due date" },
  { text: "↓ Add Todo → text + date + time required", arrow: true },
  { text: "Set Priority (low / mid / high) + Category (finance / study / work / other)" },
  { text: "↓ Attach images (max 2MB) or files (max 5MB), up to 5 per todo", arrow: true },
  { text: "Use voice input 🎤 → Speech Recognition fills text field" },
  { text: "↓ Todo saved → grouped by date, sorted by priority within group", arrow: true },
  { text: "Filter by Status (All / Active / Completed / Overdue) or Category" },
  { text: "↓ Search with debounce → highlights matching text inline", arrow: true },
  { text: "Edit inline → update text, date, priority, category, attachments" },
  { text: "↓ Toggle complete → card turns green, strikethrough applied", arrow: true },
  { text: "Clear Completed → bulk delete all completed todos" },
  { text: "↓ Download filtered todos as CSV or PDF", arrow: true },
  { text: "Toggle dark/light mode → persists via localStorage ☀️🌙" },
],

routes: [
  { icon: "📋", label: "Todo List (Single Page App)" },
],

techStack: [
  { name: "React 18", desc: "useState, useEffect, useRef, useContext — no routing needed" },
  { name: "Context API", desc: "TodoContext — centralized todos, filters, theme, all CRUD operations" },
  { name: "TailwindCSS v4", desc: "@custom-variant dark, utility-first with dynamic class composition" },
  { name: "Web Speech API", desc: "SpeechRecognition for voice-to-text input in TodoForm" },
  { name: "FileReader API", desc: "Reads image and file attachments as base64 data URLs" },
  { name: "jsPDF", desc: "Dynamic import from CDN — generates landscape PDF export" },
  { name: "localStorage", desc: "Todos and theme persisted across refresh via useEffect sync" },
  { name: "Vite", desc: "Fast dev server and build tool" },
],

highlights: [
  { label: "Date Grouping", desc: "Todos grouped by due date with Today / Tomorrow labels, sorted chronologically" },
  { label: "Priority Sorting", desc: "Within each date group, high → mid → low priority order applied automatically" },
  { label: "Overdue Detection", desc: "isOverdue() checks dueDate < now for incomplete todos — red card highlight" },
  { label: "Search Highlight", desc: "highlightText() splits todo text by query and wraps matches in <mark> inline" },
  { label: "Debounced Search", desc: "300ms debounce on search input via useRef timer — avoids re-filter on every keystroke" },
  { label: "Attachment System", desc: "Images (max 2MB) and files (max 5MB), up to 5 per todo, stored as base64 in localStorage" },
  { label: "Voice Input", desc: "Web Speech API with continuous + interim results, stop on form submit or manually" },
  { label: "Dark Mode", desc: "theme state in context, persisted to localStorage, @custom-variant dark in Tailwind v4" },
  { label: "Error Boundary", desc: "Wraps TodoList — catches render crashes, shows fallback UI with refresh prompt" },
  { label: "Download Disabled on Category Filter", desc: "CSV/PDF export blocked when categoryFilter is active to avoid partial data confusion" },
  {label:"Localstorage" , desc:"data remains after refresh "}
],

errorFlows: [
  {
    title: "Todo render crash",
    steps: [
      { text: "TodoList or TodoItem throws during render" },
      { text: "Unexpected JS error fires", type: "trigger" },
      { text: "ErrorBoundary wrapping TodoList catches it" },
      { text: "'Something went wrong ⚠️' fallback shown", type: "ok" },
    ],
  },
  {
    title: "Attachment too large",
    steps: [
      { text: "User selects file > 5MB (or image > 2MB)" },
      { text: "file.size > maxSize check fires", type: "trigger" },
      { text: "File skipped silently in loop" },
      { text: "Other valid files still attach", type: "ok" },
    ],
  },
  {
    title: "PDF generation fails",
    steps: [
      { text: "User clicks Download → PDF" },
      { text: "jsPDF CDN import or generation throws", type: "trigger" },
      { text: "try/catch in downloadTodoPDF catches it" },
      { text: "'PDF download failed' alert shown", type: "ok" },
    ],
  },
  {
    title: "Empty download attempt",
    steps: [
      { text: "User clicks Download with no visible todos" },
      { text: "filteredTodos.length === 0", type: "trigger" },
      { text: "Early guard check fires" },
      { text: "'No visible todos to download' alert shown", type: "ok" },
    ],
  },
],
      github: "https://github.com/mayurpanchal-12/ReactTodo.git",
      live: "https://react-todo-sage-phi.vercel.app/",
      status: "Completed",
    },
     {
      id: "Password Generator",
      name: "Advanced Password Generator",
      desc: "Secure password generator with strength insights, history tracking, and  guidance",
      longDesc: "Developed a feature-rich password generator with customizable settings, real-time strength indicators, password history management, and PWA support, along with clipboard functionality and security best-practice guidance.",
      tech: [
  "React 18",
  "Context API",
  "React Router",
  "Vite",
  "PWA (Progressive Web App)",
  "React Toastify",
  "JavaScript (ES6+)",
  "HTML & Tailwind CSS",
  "LocalStorage",
  "Web Clipboard API",
  "Vercel",
  "GitHub"
],
      features: [
  "Password length selector",
  "Include digits",
  "Include letters",
  "PWA support",
  "Copy to clipboard",
  "Theme toggle",
  "Localstorage",
  "Password strength indicator",
  "Recent passwords",
  "Password history",
  "Clear all",
  "Delete individual password",
  "Password guide"
],appFlow: [
  { text: "Open App → Password auto-generated on load" },
  { text: "↓ Adjust length (4–32) via range slider", arrow: true },
  { text: "Toggle Special Characters and/or Numbers" },
  { text: "↓ Strength score updates live (Weak / Medium / Strong)", arrow: true },
  { text: "Copy password → toast confirms 'Copied to clipboard! ✅'" },
  { text: "↓ Every generated password saved to History (max 10)", arrow: true },
  { text: "View History page → see all saved passwords with strength badge" },
  { text: "↓ Copy or delete individual passwords from History", arrow: true },
  { text: "Clear All → confirmation toast before wiping history" },
  { text: "↓ View Guide page → password security tips and best practices", arrow: true },
  { text: "Install as PWA → 📲 Install button appears in Navbar if installable" },
],

routes: [
  { icon: "🔑", label: "Generator (Home)" },
  { icon: "🕐", label: "History" },
  { icon: "📖", label: "Guide" },
  { icon: "⚠️", label: "404 Wildcard" },
],

techStack: [
  { name: "React 18", desc: "useState, useEffect, useCallback, useRef, useId — no Redux needed" },
  { name: "React Router v6", desc: "BrowserRouter, Routes, Route, NavLink, wildcard (*) route" },
  { name: "Context API", desc: "PasswordContext — password state, history, strength, PWA install prompt" },
  { name: "react-hot-toast", desc: "Toast notifications + inline confirmation dialogs for delete and clear" },
  { name: "TailwindCSS v4", desc: "@custom-variant dark — dark mode via .dark class on <html>" },
  { name: "Vite PWA Plugin", desc: "registerSW() in main.jsx — installable on mobile and desktop, works offline" },
  { name: "Web Clipboard API", desc: "navigator.clipboard.writeText() for one-click copy" },
  { name: "localStorage", desc: "passlength, char, num toggles, and full password history persisted" },
],

highlights: [
  { label: "PWA Support", desc: "registerSW({ immediate: true }) + beforeinstallprompt event — Install button appears automatically when browser detects installability" },
  { label: "Strength Calculator", desc: "calculateStrength() scores length (8+, 12+) and enabled options — returns Weak / Medium / Strong live as settings change" },
  { label: "Inline Confirm Toasts", desc: "react-hot-toast used as a modal replacement — delete and clear show Cancel + Confirm inside the toast itself" },
  { label: "Auto-generate on Change", desc: "generatePassword wrapped in useCallback, fires automatically via useEffect whenever length, char, or num changes" },
  { label: "History Cap", desc: "History sliced to last 10 entries on every generate — prevents unbounded localStorage growth" },
  { label: "Dark Mode", desc: "Theme component toggles .dark on <html>, Tailwind @custom-variant dark applies — no flash, no persistence bug (note: theme resets on refresh)" },
  {label:"Copy" , desc:"Copy password to Clipboard"},
  {label:"Localstorage" , desc:"Localstorage support"},
  { label: "Responsive Install Button", desc: "Two separate install buttons in Navbar — full pill button on sm+, icon-only circle on mobile" },
  { label: "Error Boundary", desc: "Wraps each route individually — Generator, History, Guide all isolated so one crash doesn't break the others" },
  { label: "404 Page", desc: "Wildcard route with Go Home + Go Back buttons, gradient 404 heading, glass card style matching app theme" },
],

errorFlows: [
  {
    title: "Both options unchecked",
    steps: [
      { text: "User unchecks Special and Numbers" },
      { text: "!char && !num check fires", type: "trigger" },
      { text: "generatePassword() sets currentPass to ''" },
      { text: "Empty password shown, no crash", type: "ok" },
    ],
  },
  {
    title: "Route render crash",
    steps: [
      { text: "PassGen / History / Guide throws during render" },
      { text: "Unexpected JS error fires", type: "trigger" },
      { text: "Per-route ErrorBoundary catches it" },
      { text: "'Something went wrong ⚠️' fallback shown", type: "ok" },
    ],
  },
  {
    title: "Unknown route",
    steps: [
      { text: "User visits /randompage" },
      { text: "No matching route found", type: "trigger" },
      { text: "Wildcard (*) route catches it" },
      { text: "404 page with Go Home / Go Back shown", type: "ok" },
    ],
  },
  {
    title: "PWA already installed",
    steps: [
      { text: "User installs the PWA" },
      { text: "appinstalled event fires", type: "trigger" },
      { text: "isInstallable set to false" },
      { text: "Install button removed from Navbar", type: "ok" },
    ],
  },
],
      github: "https://github.com/mayurpanchal-12/Password-Generator.git",
      live: "https://password-generator-three-ashen.vercel.app/",
      status: "Completed",
    },


{
  id: "portfolio",
  name: "Portfolio Website",
  desc: "Personal dev portfolio with a code-editor aesthetic built in React.",
  longDesc: "A fully responsive personal portfolio built from scratch using React, React Router and TailwindCSS. Features a dark code-editor aesthetic with syntax-highlighted UI cards, animated code blocks, dynamic project detail pages driven by a single data file, EmailJS contact form with no backend, and a downloadable resume.",
  tech: ["React 18", "React Router v6", "TailwindCSS v4", "EmailJS", "Fira Code", "Lucid-react","Vite", "Vercel"],
  features: [
    "Dark code-editor theme with syntax colours",
    "Syntax-highlighted project cards",
    "Dynamic project detail pages",
    "EmailJS contact form — no backend",
    "Downloadable resume via reloadDocument",
    "React.lazy + Suspense on ProjectDetail",
    "Per-route Error Boundary",
    "404 wildcard page",
    "Fully responsive — 320px to desktop",
  ],
  appFlow: [
    { text: "Land on Home → code card + skills intro" },
    { text: "↓ Scroll down → About intro + Projects + Contact all on Home", arrow: true },
    { text: "Visit /about → full profile, education timeline, projects grid" },
    { text: "↓ Click 'view details' → navigates to /projects/:id", arrow: true },
    { text: "ProjectDetail loads lazily → PageLoader spinner shown" },
    { text: "↓ Detail page shows flow, routes, tech, highlights, error flows", arrow: true },
    { text: "Visit /contact → fill name, email, message → send()" },
    { text: "↓ EmailJS sends email → success/error feedback shown inline", arrow: true },
    { text: "Visit unknown route → 404 Wildcard page" },
  ],
  routes: [
    { icon: "🏠", label: "Home" },
    { icon: "👤", label: "About" },
    { icon: "💻", label: "Projects" },
    { icon: "🔍", label: "Project Detail (/projects/:id)" },
    { icon: "📞", label: "Contact" },
    { icon: "🪪", label: "Intro" },
    { icon: "⚠️", label: "404 Wildcard" },
  ],
  techStack: [
    { name: "React 18", desc: "lazy, Suspense, useState, useNavigate — no Redux needed" },
    { name: "React Router v6", desc: "createBrowserRouter, createRoutesFromElements, nested routes under Layout" },
    { name: "TailwindCSS v4", desc: "@custom-variant dark, utility classes mixed with custom CSS files per page" },
    { name: "EmailJS", desc: "fetch() to api.emailjs.com — sends emails from browser, free tier 200/month" },
    { name: "Custom CSS modules", desc: "Per-page CSS files for BEM-style component classes alongside Tailwind" },
    { name: "Fira Code", desc: "Monospace font giving the code-editor aesthetic throughout" },
    { name: "Vite", desc: "Fast dev server, reloadDocument for resume PDF download" },
    { name: "Vercel", desc: "Deployment with automatic preview on push" },
  ],
  highlights: [
    { label: "Single Data File", desc: "All project info lives in projectsData.js — update one file, every page (Home, About, Projects, ProjectDetail) reflects it automatically" },
    { label: "Dynamic Detail Pages", desc: "ProjectDetail reads :id from URL, finds the matching project object, and renders appFlow, routes, techStack, highlights and errorFlows sections conditionally" },
    { label: "Code-editor Aesthetic", desc: "Syntax colours (c-keyword, c-string, c-bool, c-fn) applied via CSS classes — cards look like real JS objects with bracket syntax" },
    { label: "EmailJS — No Backend", desc: "Contact form POSTs directly to EmailJS API with fetch() — no server, no env variables exposed, works on free Vercel deployment" },
    { label: "Lazy + Suspense", desc: "ProjectDetail is the only lazy-loaded page since it's data-heavy — others are small enough to not need it" },
    { label: "Per-route Error Boundary", desc: "Projects and ProjectDetail each have their own ErrorBoundary — a crash in one doesn't affect the rest of the app" },
    { label: "Resume Download", desc: "reloadDocument on the resume Link forces a full browser download of /resume.pdf without React Router intercepting it" },
    { label: "Responsive Navbar", desc: "Sticky top navbar with NavLink active state, gradient underline decoration, Code2 icon from lucide-react" },
  ],
  errorFlows: [
    {
      title: "Invalid project ID",
      steps: [
        { text: "User visits /projects/unknownid" },
        { text: "projects.find() returns undefined", type: "trigger" },
        { text: "if (!project) check fires" },
        { text: "throw 'project not found' UI shown", type: "ok" },
      ],
    },
    {
      title: "ProjectDetail render crash",
      steps: [
        { text: "ProjectDetail throws during render" },
        { text: "Unexpected JS error fires", type: "trigger" },
        { text: "ErrorBoundary on /projects/:id catches it" },
        { text: "'Something went wrong ⚠️' + Try Again shown", type: "ok" },
      ],
    },
    {
      title: "Contact form send fails",
      steps: [
        { text: "User submits contact form" },
        { text: "EmailJS fetch() rejects or returns non-ok", type: "trigger" },
        { text: ".catch() / else branch fires" },
        { text: "status = 'error' → '✗ something went wrong' shown", type: "ok" },
      ],
    },
    {
      title: "Unknown route",
      steps: [
        { text: "User visits /randompage" },
        { text: "No matching route found", type: "trigger" },
        { text: "Wildcard (*) route catches it" },
        { text: "404 page with Go Home button shown", type: "ok" },
      ],
    },
  ],
  github: "https://github.com/mayurpanchal-12/Personal_portfolio_React.js.git",
  live: "https://personal-portfolio-react-js-psi.vercel.app/",
  status: "Completed",
},
  ];
