export const projects = [



    {
      id: "Finance Tracker",
      name: "Advanced Finance Tracker",
      desc: "helps users manage Transactions , future transactions, analytics,budget  and financial news",
      longDesc:"A full-featured Finance Tracker web app to manage income, expenses, budgets, future transactions, analytics, and financial news in one place. It includes voice input, advanced search/filtering, interactive charts, and CSV/PDF export , PWA support with real-time balance updates. Built using Firebase (Auth + Firestore) and Cloudinary for secure, scalable data and file management. it has RBAC viewer set by admin only see transactions",
      tech: [
  "React.js",
  "Context API",
  "Tailwind CSS",
  "JavaScript (ES6+)",
  "Browser Speech API",
  "Chart.js",
  "CSV / PDF export utilities",
  "Alpha Vantage API",
  "Firebase",
  "Cloudinary",
  "Vercel",
  "Github"
],
      features: ["Transaction Management" , "Filter & Search" , "Insights (Income) & Budget " ,"Download-Csv & PDF" ,"PWA" , "Vault", "Schedule Transactions " , "Charts & Analytics" , "Summary" , "notes" , "News" , "Bedget , insights , Skeleton Loading , Lazy + Suspense"],
     
   appFlow: [
  { text: "Open App → Firebase checks auth state" },
  { text: "↓ Not logged in → LoginPage (Google OAuth or Email/Password)", arrow: true },
  { text: "Role check → admin or viewer (from Firestore viewerProfiles)" },
  { text: "↓ Viewer mode → read-only, sees admin's data ✅", arrow: true },
  { text: "View Transaction Tracker (Home)" },
  { text: "↓ Add / Edit / Delete Transactions [admin only]", arrow: true },
  { text: "Voice input via mic → speech-to-text fills form fields" },
  { text: "↓ Star / highlight important transactions → auto-highlights top 2 on 10+ rows", arrow: true },
  { text: "Set future-dated transaction → Scheduled Transactions table [admin only]" },
  { text: "↓ On scheduled date → auto-moves to main Tracker ✅", arrow: true },
  { text: "Filter by Month / Type / Category / Search" },
  { text: "↓ View filtered results in table + Summary", arrow: true },
  { text: "Export filtered data → CSV or PDF via DownloadDropdown" },
  { text: "↓ View Charts → Line chart + Income/Expense pie charts", arrow: true },
  { text: "View Insights → Monthly comparison + Smart observations banner" },
  { text: "↓ View Budget → Set limits per category → over/near 80% alerts [admin only]", arrow: true },
  { text: "View Notes → all transactions with notes listed" },
  { text: "↓ View Vault → upload receipts / documents / images (Cloudinary)", arrow: true },
  { text: "View News → Finance headlines from Alpha Vantage API" },
  { text: "↓ News loader fails → NewsErrorPage shown ✅", arrow: true },
  { text: "Manage Viewers → add/remove viewer accounts [admin only]" },
  { text: "↓ Install as PWA → works offline via service worker", arrow: true },
  { text: "Delete Account → permanently removes account + all data [admin only]" },
  { text: "↓ View About → feature overview page", arrow: true },
  { text: "Unknown route → Wildcard 404 page shown ✅" },
],
routes: [
  { icon: "📋", label: "Tracker (Home)" },
  { icon: "➕", label: "Set Transaction" },
  { icon: "📅", label: "Scheduled Transactions" },
  { icon: "📊", label: "Charts" },
  { icon: "💡", label: "Insights" },
  { icon: "💰", label: "Budget" },
  { icon: "📝", label: "Notes" },
  { icon: "🗄️", label: "Vault" },
  { icon: "📰", label: "News" },
  { icon: "⚠️", label: "News Error" },
  { icon: "👥", label: "Manage Viewers" },
  { icon: "ℹ️", label: "About" },
  { icon: "❓", label: "404 Wildcard" },
],
techStack: [
  { name: "React 18", desc: "Hooks, lazy, Suspense for code-split page loading" },
  { name: "React Router v6", desc: "createBrowserRouter, loader, errorElement, wildcard route" },
  { name: "Firebase Auth", desc: "Google OAuth + email/password login, auth state persistence" },
  { name: "Firestore", desc: "Real-time database for transactions, viewer profiles and budget" },
  { name: "Context API + useReducer", desc: "TransactionContext — centralized state, no prop drilling" },
   { name: "Cloudinary", desc: "Cloud storage for receipts, documents and images in Vault" },
  { name: "TailwindCSS", desc: "Utility-first styling with custom CSS variables and @layer" },
  { name: "Chart.js", desc: "Dynamic line + pie charts for income/expense analysis" },
  { name: "Alpha Vantage API", desc: "Live finance news fetched via route loader" },
  { name: "Browser Speech API", desc: "Voice input via mic — speech-to-text fills form fields" },
  { name: "PWA + Service Worker", desc: "Installable app with offline support" },
  { name: "Vite", desc: "Fast build tool with import.meta.env for API key" },
],

highlights: [
  { label: "Firebase Auth", desc: "Google OAuth + email/password login with persistent auth state and role-based access control" },
  { label: "Role-based Access", desc: "Admin vs viewer roles from Firestore — viewers see admin's data in read-only mode" },
  { label: "Scheduled Transactions", desc: "Future-dated entries sit in a separate table and auto-promote to main tracker on their date" },
  { label: "Voice Input", desc: "useSpeechInput hook enables voice-to-text via Browser Speech API in the transaction form" },
  { label: "Star / Highlight", desc: "Manually star important transactions — auto-highlights top 2 rows when table has 10+ entries" },
  { label: "Budget Alerts", desc: "Set spending limits per category — warns when over or near 80% of the budget" },
  { label: "Vault", desc: "Upload and store receipts, documents and images via Cloudinary integration" },
  { label: "CSV + PDF Export", desc: "DownloadDropdown lets users export filtered transaction data in two formats" },
  { label: "Charts", desc: "Analytics with overall balance line chart and income/expense pie charts" },
  { label: "Insights", desc: "Monthly comparison and smart observations banner for spending patterns" },
  { label: "Manage Viewers", desc: "Admin can add or remove viewer accounts directly from the app" },
  { label: "PWA + Offline", desc: "Installable as a PWA — works offline via service worker" },
  { label: "Delete Account", desc: "Permanently removes the account and all associated data — admin only" },
  { label: "Route-level Error Handling", desc: "News route uses errorElement: <NewsErrorPage /> for loader failures" },
  { label: "Code Splitting", desc: "All pages are React.lazy with Suspense + PageLoader fallback — only loads what's needed" },
  { label: "Running Balance", desc: "Each filtered transaction gets a live-computed balance column via useMemo" },
  { label: "Responsive Design", desc: "Mobile-first layout using Tailwind, max-w-[1200px] centered root, flex-col gap structure" },
],

errorFlows: [
  {
    title: "News API fails",
    steps: [
      { text: "User navigates to /news" },
      { text: "newsLoader() throws", type: "trigger" },
      { text: "React Router catches loader error" },
      { text: "errorElement: <NewsErrorPage /> shown", type: "ok" },
    ],
  },
  {
    title: "Page render crash",
    steps: [
      { text: "ChartPage / NotesPage / etc renders" },
      { text: "Unexpected JS error thrown", type: "trigger" },
      { text: "ErrorBoundary catches it" },
      { text: "Fallback UI + Try Again shown", type: "ok" },
    ],
  },
  {
    title: "Unknown route",
    steps: [
      { text: "User visits /randompage" },
      { text: "No matching route found", type: "trigger" },
      { text: "Wildcard (*) catches it" },
      { text: "404 Page shown", type: "ok" },
    ],
  },
  {
    title: "Not logged in",
    steps: [
      { text: "User opens the app" },
      { text: "Firebase auth state is null", type: "trigger" },
      { text: "Auth check fires on load" },
      { text: "LoginPage shown", type: "ok" },
    ],
  },
  {
    title: "Viewer tries admin action",
    steps: [
      { text: "Viewer is logged in" },
      { text: "Attempts to add / edit / delete", type: "trigger" },
      { text: "Role check returns 'viewer'" },
      { text: "Action blocked — read-only mode", type: "ok" },
    ],
  },
  {
    title: "No transactions with notes",
    steps: [
      { text: "User opens /notes" },
      { text: "transactionsWithNotes.length === 0", type: "trigger" },
      { text: "Empty state check fires" },
      { text: "'No notes yet' message shown", type: "ok" },
    ],
  },
  {
    title: "Vault upload fails",
    steps: [
      { text: "User uploads a file in /vault" },
      { text: "Cloudinary request fails", type: "trigger" },
      { text: "Upload error caught" },
      { text: "Error message shown to user", type: "ok" },
    ],
  },
],
      github: "https://github.com/mayurpanchal-12/FinanceTracker_Reactjs.git",
      live: "https://finance-tracker-reactjs-sandy.vercel.app/",
      status: "Completed",
      
    },
    {
      id: "Advance Todo Manager",
      name: "Task Flow",
    desc: "Production-grade React task manager with Kanban board, calendar view, Pomodoro timer, analytics dashboard, voice input, Firebase Auth, Firestore sync, and PWA support.",

longDesc: "Full-featured task management SPA built with React and Context API with real-time Firestore sync and  Firebase Auth. Features drag-and-drop Kanban board, monthly calendar, 28-day activity heatmap, per-task Pomodoro timer, repeating tasks, project workspaces, tag filtering, and CSV/PDF export. Supports voice input , file attachments via Cloudinary, Theme Toggle , PWA.",
  tech: [
  "React 18",
  "Vite",
  "Context API",
  "JavaScript (ES6+)",
  "Firebase Auth",
  "Firestore",
  "Cloudinary",
  "Web Speech API",
  "CSS Custom Properties",
  "Drag and Drop API",
  "jsPDF",
  "PWA + Service Worker",
  "Vercel",
  "Github"
],

 
features: [
  "CRUD Tasks",
  "Project Workspaces",
  "Kanban Board (Drag & Drop)",
  "Calendar View",
  "Analytics Dashboard + Heatmap",
  "Pomodoro Timer",
  "Subtasks",
  "Repeating Tasks",
  "Pinned Tasks",
  "Tag Filtering",
  "Today's Focus Mode",
  "Voice Input",
  "File Attachments (Cloudinary)",
  "CSV + PDF Export",
  "Activity History",
  "Search & Filters",
  "Dark / Light Mode",
  "Firebase Auth",
  "Firestore Real-time Sync",
  "PWA + Offline Support",
  "Skeleton Loading",
  "Error Boundary",
  "Code Splitting",
  "Delete Account",
],
appFlow: [
  { text: "Open App → Firebase checks auth state" },
  { text: "↓ Not logged in → LoginPage (Google OAuth or Email/Password)", arrow: true },
  { text: "Logged in → Firestore loads user data via real-time onSnapshot listener" },
  { text: "↓ Skeleton placeholders shown while data loads", arrow: true },
  { text: "View All Tasks → grouped by due date, sorted by priority" },
  { text: "↓ Add Task → title, due date + time, priority, category, project, tags, subtasks, repeat, attachments, pin", arrow: true },
  { text: "Voice input via mic → Web Speech API fills task name hands-free" },
  { text: "↓ Attach images (max 2MB) or files (max 5MB) via Cloudinary — up to 5 per task", arrow: true },
  { text: "Start Pomodoro Timer → 25min work / 5min break cycles linked to task" },
  { text: "↓ Repeating task completed → auto-clones with next due date ✅", arrow: true },
  { text: "Switch to Board view → drag and drop between To Do / In Progress / Done" },
  { text: "↓ Switch to Calendar view → browse tasks by due date on monthly grid", arrow: true },
  { text: "Switch to History view → activity log of created / edited / completed / deleted" },
  { text: "↓ Filter by status / category / tag / Today's Focus", arrow: true },
  { text: "Pinned panel → quick-access pinned tasks, click to scroll + flash highlight" },
  { text: "↓ Projects panel → create color-labeled workspaces, scope all views per project", arrow: true },
  { text: "Analytics Dashboard → completion rate, category breakdown, 28-day heatmap" },
  { text: "↓ Export filtered tasks → CSV or PDF via Export dropdown", arrow: true },
  { text: "Toggle dark / light mode → persisted to Firestore per user" },
  { text: "↓ Install as PWA → works offline via service worker", arrow: true },
  { text: "Delete Account → re-authenticates via Google popup, then deletes Firebase user ✅" },
  { text: "↓ Unknown route → Wildcard 404 page shown ✅", arrow: true },
],

routes: [
  { icon: "🏠", label: "App (Single Page)" },
  { icon: "🔐", label: "Login / Signup" },
  { icon: "📋", label: "List View" },
  { icon: "🗃️", label: "Kanban Board" },
  { icon: "📅", label: "Calendar View" },
  { icon: "🕐", label: "Activity History" },
  { icon: "📊", label: "Analytics Dashboard" },
  { icon: "📁", label: "Projects" },
  { icon: "📌", label: "Pinned Tasks" },
  { icon: "🏷️", label: "Tags" },
  { icon: "🎯", label: "Today's Focus" },
  { icon: "⏱️", label: "Pomodoro Timer" },
  { icon: "⚠️", label: "Error Boundary" },
  { icon: "❓", label: "404 Wildcard" },
],


  techStack: [
  { name: "React 18", desc: "Hooks, Context, class-based ErrorBoundary, code splitting via lazy + Suspense" },
  { name: "Context API", desc: "Single TodoContext — todos, filters, theme, projects, history, pins, all CRUD" },
  { name: "Firebase Auth", desc: "Google OAuth + email/password login, account deletion with re-auth" },
  { name: "Firestore", desc: "Real-time onSnapshot listener, debounced writes (600ms), per-user doc" },
  { name: "Cloudinary", desc: "File and image upload per task, unsigned preset, no backend needed" },
  { name: "Web Speech API", desc: "SpeechRecognition for voice-to-text input in task form" },
  { name: "Drag and Drop API", desc: "Native HTML5 DnD for Kanban board column transitions — no library needed" },
  { name: "jsPDF", desc: "Generates landscape PDF export of filtered task list" },
  { name: "CSS Custom Properties", desc: "Full design token system — colors, spacing, typography, dark/light remapping" },
  { name: "PWA + Service Worker", desc: "vite-plugin-pwa — installable, works offline, install prompt captured globally" },
  { name: "Vite", desc: "Fast dev server, import.meta.env for secure API keys, PWA plugin" },
],

highlights: [
  { label: "Firebase Auth", desc: "Google OAuth + email/password login, account deletion with automatic re-auth if session is stale" },
  { label: "Firestore Sync", desc: "Real-time onSnapshot listener with debounced writes (600ms) — skipNextSave ref prevents infinite loop" },
  { label: "Role Isolation", desc: "All data scoped to users/{uid} in Firestore — users can only access their own document" },
  { label: "Kanban Board", desc: "Drag-and-drop across To Do / In Progress / Done using native HTML5 Drag API — no library needed" },
  { label: "Pomodoro Timer", desc: "Floating widget with 25min work / 5min break cycles, circular SVG progress ring, linked to specific task" },
  { label: "Repeating Tasks", desc: "On completion, auto-clones with next due date calculated — original marked complete immediately" },
  { label: "Analytics Dashboard", desc: "Completion rate, category breakdown, status overview, and 28-day activity heatmap with best-day highlight" },
  { label: "Calendar View", desc: "Monthly grid with prev / next / today navigation — tasks plotted by due date, respects active filters" },
  { label: "Activity History", desc: "Log of up to 300 create / edit / complete / delete actions with time-ago labels and timestamps" },
  { label: "Project Workspaces", desc: "Color-labeled workspaces — all views scope per project, completion percentage shown in quick-stats bar" },
  { label: "Pinned Tasks", desc: "Pin any task for sidebar quick-access — click to scroll to task and flash highlight it" },
  { label: "Tag System", desc: "Custom tags with deterministic colors — sidebar tag panel filters full task list, count shown per chip" },
  { label: "Today's Focus", desc: "Filters to today's tasks + all overdue active tasks — red badge shows urgency count" },
  { label: "Voice Input", desc: "Web Speech API with continuous recognition — transcript appended to task title in real time" },
  { label: "File Attachments", desc: "Images (max 2MB) and files (max 5MB) via Cloudinary — up to 5 per task, thumbnails shown inline" },
  { label: "Subtasks", desc: "Nested subtask checklist with independent completion tracking and progress visible on task card" },
  { label: "Debounced Search", desc: "searchInput updates instantly for UI; searchQuery applies on delay — all filters composable" },
  { label: "CSV + PDF Export", desc: "Export filtered task list — disabled when category filter active to avoid partial data" },
  { label: "Dark / Light Mode", desc: "Full CSS token remapping — not inverted. Theme persisted to Firestore and syncs across devices" },
  { label: "PWA + Offline", desc: "vite-plugin-pwa — installable via quick-stats bar, works offline via service worker" },
  { label: "Delete Account", desc: "Re-authenticates via Google popup before deletion — prevents accidental removal with stale session" },
  { label: "Error Boundary", desc: "Catches render crashes — two recovery options: Try Again resets state, Reload hard-resets the page" },
  { label: "Code Splitting", desc: "All pages React.lazy + Suspense with skeleton placeholders while Firestore data loads" },
  { label: "Responsive Design", desc: "Mobile-first layout — Pomodoro becomes bottom sheet, tabs collapse to icons on small screens" },
],

errorFlows: [
  {
    title: "Page render crash",
    steps: [
      { text: "Any component throws a JS error" },
      { text: "Unexpected error fires", type: "trigger" },
      { text: "ErrorBoundary catches it" },
      { text: "'Something went wrong' + Try Again / Reload shown", type: "ok" },
    ],
  },
  {
    title: "File upload fails",
    steps: [
      { text: "User attaches a file in task form" },
      { text: "Cloudinary request fails", type: "trigger" },
      { text: "Error caught — task saved without attachment" },
      { text: "Task saved successfully without file", type: "ok" },
    ],
  },
  {
    title: "Empty export attempt",
    steps: [
      { text: "User clicks Export with no visible tasks" },
      { text: "filteredTodos.length === 0", type: "trigger" },
      { text: "Early guard fires before generation" },
      { text: "Alert shown before CSV / PDF attempted", type: "ok" },
    ],
  },
  {
    title: "Account delete — stale session",
    steps: [
      { text: "User clicks Delete Account" },
      { text: "auth/requires-recent-login caught", type: "trigger" },
      { text: "Re-auth popup triggered automatically" },
      { text: "Deletion proceeds after re-auth ✅", type: "ok" },
    ],
  },
  {
    title: "No tasks match filters",
    steps: [
      { text: "User applies status / category / tag filter" },
      { text: "filteredTodos.length === 0", type: "trigger" },
      { text: "Empty state check fires" },
      { text: "Contextual empty message shown ✅", type: "ok" },
    ],
  },
  {
    title: "Not logged in",
    steps: [
      { text: "User opens the app" },
      { text: "Firebase auth state is null", type: "trigger" },
      { text: "Auth check fires on load" },
      { text: "LoginPage shown", type: "ok" },
    ],
  },
  {
    title: "Unknown route",
    steps: [
      { text: "User visits /randompage" },
      { text: "No matching route found", type: "trigger" },
      { text: "Wildcard (*) catches it" },
      { text: "404 Page shown", type: "ok" },
    ],
  },
],
 
      github: "https://github.com/mayurpanchal-12/ReactTodo.git",
      live: "https://react-todo-sage-phi.vercel.app/",
      status: "Completed",
    },
    {
  id: "wristly",
  name: "Wristly",
  desc: "Premium watch e-commerce app built with React.js and TailwindCSS.",
  longDesc: "A production-grade premium watch e-commerce application built with React, showcasing modern frontend practices, state management, and performance optimization.",
  tech: ["React.js", "JavaScript (ES6+)", "Redux", "TailwindCSS", "Vite", "React Router DOM", "Local Storage","Vite PWA","Lucid-react", "react-toastify","swiper-slider","Skeleton-loading", "Vercel"],
  features: [
    "Filter, Search, and Sort products (combined logic)",
    "Product detail page with image gallery",
    "Cart with quantity management",
    "Wishlist toggle (single action)",
    "Authentication (localStorage-based)",
    "Checkout flow with order confirmation",
    "Skeleton loading UI",
    "Theme Toggler",
    "Prop Types",
    "Error Boundary",
    "PWA support",
    "React Lazy + Suspense",
  ],
  appFlow: [
    { text: "Browse Products → Filter / Search / Sort" },
    { text: "↓ Add to Wishlist (saves across refresh)", arrow: true },
    { text: "Add to Cart → quantity selected" },
    { text: "↓ Proceed to Checkout", arrow: true },
    { text: "Not logged in → Login Wall → Login / Signup" },
    { text: "↓ Fill Delivery Address + Select Payment", arrow: true },
    { text: "placeOrder() → Cart Clears → Order Confirmed ✓" },
  ],
  routes: [
    { icon: "🏠", label: "Home" },
    { icon: "🔍", label: "Browse Products" },
    { icon: "🛍️", label: "Product Details" },
    { icon: "❤️", label: "Wishlist" },
    { icon: "🛒", label: "Cart" },
    { icon: "💳", label: "Checkout" },
    { icon: "✅", label: "Order Confirm" },
    { icon: "👤", label: "My Account" },
    { icon: "🔐", label: "Login / Signup" },
    { icon: "ℹ️", label: "About" },
    { icon: "❓", label: "FAQ" },
    { icon: "📞", label: "Contact" },
    { icon: "⚠️", label: "404 Page" },
  ],
  techStack: [
    { name: "React 18", desc: "Hooks, lazy, Suspense for code splitting" },
    { name: "Redux Toolkit", desc: "createSlice, createAsyncThunk, store.subscribe for persistence" },
    { name: "React Router v6", desc: "Client-side routing with protected routes" },
    { name: "TailwindCSS", desc: "Utility-first styling with custom CSS variables" },
    { name: "Vite", desc: "Fast build tool and dev server" },
    { name: "localStorage", desc: "Cart, wishlist and auth persistence across refresh" },
    { name: "lucide-react", desc: "Icons — Heart, Cart, User, Menu, Trash etc." },
    { name: "react-toastify", desc: "Toast notifications for user actions" },
    { name: "swiper", desc: "Hero slider and related products carousel" },
    { name: "react-loading-skeleton", desc: "Skeleton loading UI for better UX" },
    {name:"Vite PWA" , desc:"PWA installation"}
  ],
  highlights: [
    { label: "Dark Mode", desc: "CSS variables + .dark on <html>, persists via localStorage, no flash on load" },
    { label: "PWA Support", desc: "Installable on mobile and desktop, works offline via Service Worker" },
    { label: "Redux Architecture", desc: "Centralized state, no prop drilling, store.subscribe for localStorage sync" },
    { label: "Performance", desc: "React.lazy + Suspense, React.memo, useCallback, useMemo to minimize re-renders" },
    { label: "PropTypes", desc: "Runtime prop validation on all components, catches bugs during development" },
    { label: "Error Boundary", desc: "Prevents full app crash, shows fallback UI on component errors" },
    {label:"Sliders", desc:"swiper slider enhanced UI/UX"},
    {label:"Skeleton-Loading" , desc:"enhanced UI/UX"},
  
    { label: "Auth Flow", desc: "Signup / Login stored in localStorage, logout clears session only" },
    {label:"Localstorage" , desc:"data remains after refresh"},
    {label:"toast", desc:"Toast alerts using Toastify"},
      { label: "Responsive Design", desc: "320px to desktop, Tailwind + custom CSS, mobile-first layout" },
  ],
  errorFlows: [
    {
      title: "Invalid product ID",
      steps: [
        { text: "User visits /ProductDetails/999" },
        { text: "product = undefined", type: "trigger" },
        { text: "if (!product) check fires" },
        { text: "'Product not found' UI shown", type: "ok" },
      ],
    },
    {
      title: "Undefined specs crash",
      steps: [
        { text: "product.specs is undefined" },
        { text: "Object.entries(undefined)", type: "trigger" },
        { text: "Error Boundary catches it" },
        { text: "Fallback UI shown", type: "ok" },
      ],
    },
    {
      title: "Unknown route",
      steps: [
        { text: "User visits /randompage" },
        { text: "No matching route", type: "trigger" },
        { text: "Wildcard (*) catches it" },
        { text: "404 Page shown", type: "ok" },
      ],
    },
  ],
  github: "https://github.com/mayurpanchal-12/Wristly_React-Project",
  live: "https://wristy-react-project.vercel.app/",
  status: "Completed",
},

{
  id: "portfolio",
  name: "Portfolio Website",
  desc: "Personal dev portfolio with a code-editor aesthetic built in React.",
  longDesc: "A fully responsive personal portfolio built from scratch using React, React Router and TailwindCSS. Features a dark code-editor aesthetic with syntax-highlighted UI cards, animated code blocks, dynamic project detail pages driven by a single data file, EmailJS contact form with no backend, and a downloadable resume.",
  tech: ["React 18", "React Router v6", "TailwindCSS v4", "EmailJS", "Fira Code", "Lucid-react","Vite", "Vercel"],
  features: [
    "Dark code-editor theme with syntax colours",
    "Syntax-highlighted project cards",
    "Dynamic project detail pages",
    "EmailJS contact form — no backend",
    "Downloadable resume via reloadDocument",
    "React.lazy + Suspense on ProjectDetail",
    "Per-route Error Boundary",
    "404 wildcard page",
    "Fully responsive — 320px to desktop",
  ],
  appFlow: [
    { text: "Land on Home → code card + skills intro" },
    { text: "↓ Scroll down → About intro + Projects + Contact all on Home", arrow: true },
    { text: "Visit /about → full profile, education timeline, projects grid" },
    { text: "↓ Click 'view details' → navigates to /projects/:id", arrow: true },
    { text: "ProjectDetail loads lazily → PageLoader spinner shown" },
    { text: "↓ Detail page shows flow, routes, tech, highlights, error flows", arrow: true },
    { text: "Visit /contact → fill name, email, message → send()" },
    { text: "↓ EmailJS sends email → success/error feedback shown inline", arrow: true },
    { text: "Visit unknown route → 404 Wildcard page" },
  ],
  routes: [
    { icon: "🏠", label: "Home" },
    { icon: "👤", label: "About" },
    { icon: "💻", label: "Projects" },
    { icon: "🔍", label: "Project Detail (/projects/:id)" },
    { icon: "📞", label: "Contact" },
    { icon: "🪪", label: "Intro" },
    { icon: "⚠️", label: "404 Wildcard" },
  ],
  techStack: [
    { name: "React 18", desc: "lazy, Suspense, useState, useNavigate — no Redux needed" },
    { name: "React Router v6", desc: "createBrowserRouter, createRoutesFromElements, nested routes under Layout" },
    { name: "TailwindCSS v4", desc: "@custom-variant dark, utility classes mixed with custom CSS files per page" },
    { name: "EmailJS", desc: "fetch() to api.emailjs.com — sends emails from browser, free tier 200/month" },
    { name: "Custom CSS modules", desc: "Per-page CSS files for BEM-style component classes alongside Tailwind" },
    { name: "Fira Code", desc: "Monospace font giving the code-editor aesthetic throughout" },
    { name: "Vite", desc: "Fast dev server, reloadDocument for resume PDF download" },
    { name: "Vercel", desc: "Deployment with automatic preview on push" },
  ],
  highlights: [
    { label: "Single Data File", desc: "All project info lives in projectsData.js — update one file, every page (Home, About, Projects, ProjectDetail) reflects it automatically" },
    { label: "Dynamic Detail Pages", desc: "ProjectDetail reads :id from URL, finds the matching project object, and renders appFlow, routes, techStack, highlights and errorFlows sections conditionally" },
    { label: "Code-editor Aesthetic", desc: "Syntax colours (c-keyword, c-string, c-bool, c-fn) applied via CSS classes — cards look like real JS objects with bracket syntax" },
    { label: "EmailJS — No Backend", desc: "Contact form POSTs directly to EmailJS API with fetch() — no server, no env variables exposed, works on free Vercel deployment" },
    { label: "Lazy + Suspense", desc: "ProjectDetail is the only lazy-loaded page since it's data-heavy — others are small enough to not need it" },
    { label: "Per-route Error Boundary", desc: "Projects and ProjectDetail each have their own ErrorBoundary — a crash in one doesn't affect the rest of the app" },
    { label: "Resume Download", desc: "reloadDocument on the resume Link forces a full browser download of /resume.pdf without React Router intercepting it" },
    { label: "Responsive Navbar", desc: "Sticky top navbar with NavLink active state, gradient underline decoration, Code2 icon from lucide-react" },
  ],
  errorFlows: [
    {
      title: "Invalid project ID",
      steps: [
        { text: "User visits /projects/unknownid" },
        { text: "projects.find() returns undefined", type: "trigger" },
        { text: "if (!project) check fires" },
        { text: "throw 'project not found' UI shown", type: "ok" },
      ],
    },
    {
      title: "ProjectDetail render crash",
      steps: [
        { text: "ProjectDetail throws during render" },
        { text: "Unexpected JS error fires", type: "trigger" },
        { text: "ErrorBoundary on /projects/:id catches it" },
        { text: "'Something went wrong ⚠️' + Try Again shown", type: "ok" },
      ],
    },
    {
      title: "Contact form send fails",
      steps: [
        { text: "User submits contact form" },
        { text: "EmailJS fetch() rejects or returns non-ok", type: "trigger" },
        { text: ".catch() / else branch fires" },
        { text: "status = 'error' → '✗ something went wrong' shown", type: "ok" },
      ],
    },
    {
      title: "Unknown route",
      steps: [
        { text: "User visits /randompage" },
        { text: "No matching route found", type: "trigger" },
        { text: "Wildcard (*) route catches it" },
        { text: "404 page with Go Home button shown", type: "ok" },
      ],
    },
  ],
  github: "https://github.com/mayurpanchal-12/Personal_portfolio_React.js.git",
  live: "https://personal-portfolio-react-js-psi.vercel.app/",
  status: "Completed",
},
     {
      id: "Password Generator",
      name: "Advanced Password Generator",
      desc: "Secure password generator with strength insights, history tracking, and  guidance",
      longDesc: "Developed a feature-rich password generator with customizable settings, real-time strength indicators, password history management, and PWA support, along with clipboard functionality and security best-practice guidance.",
      tech: [
  "React 18",
  "Context API",
  "React Router",
  "Vite",
  "PWA (Progressive Web App)",
  "React Toastify",
  "JavaScript (ES6+)",
  "HTML & Tailwind CSS",
  "LocalStorage",
  "Web Clipboard API",
  "Vercel",
  "GitHub"
],
      features: [
  "Password length selector",
  "Include digits",
  "Include letters",
  "PWA support",
  "Copy to clipboard",
  "Theme toggle",
  "Localstorage",
  "Password strength indicator",
  "Recent passwords",
  "Password history",
  "Clear all",
  "Delete individual password",
  "Password guide"
],appFlow: [
  { text: "Open App → Password auto-generated on load" },
  { text: "↓ Adjust length (4–32) via range slider", arrow: true },
  { text: "Toggle Special Characters and/or Numbers" },
  { text: "↓ Strength score updates live (Weak / Medium / Strong)", arrow: true },
  { text: "Copy password → toast confirms 'Copied to clipboard! ✅'" },
  { text: "↓ Every generated password saved to History (max 10)", arrow: true },
  { text: "View History page → see all saved passwords with strength badge" },
  { text: "↓ Copy or delete individual passwords from History", arrow: true },
  { text: "Clear All → confirmation toast before wiping history" },
  { text: "↓ View Guide page → password security tips and best practices", arrow: true },
  { text: "Install as PWA → 📲 Install button appears in Navbar if installable" },
],

routes: [
  { icon: "🔑", label: "Generator (Home)" },
  { icon: "🕐", label: "History" },
  { icon: "📖", label: "Guide" },
  { icon: "⚠️", label: "404 Wildcard" },
],

techStack: [
  { name: "React 18", desc: "useState, useEffect, useCallback, useRef, useId — no Redux needed" },
  { name: "React Router v6", desc: "BrowserRouter, Routes, Route, NavLink, wildcard (*) route" },
  { name: "Context API", desc: "PasswordContext — password state, history, strength, PWA install prompt" },
  { name: "react-hot-toast", desc: "Toast notifications + inline confirmation dialogs for delete and clear" },
  { name: "TailwindCSS v4", desc: "@custom-variant dark — dark mode via .dark class on <html>" },
  { name: "Vite PWA Plugin", desc: "registerSW() in main.jsx — installable on mobile and desktop, works offline" },
  { name: "Web Clipboard API", desc: "navigator.clipboard.writeText() for one-click copy" },
  { name: "localStorage", desc: "passlength, char, num toggles, and full password history persisted" },
],

highlights: [
  { label: "PWA Support", desc: "registerSW({ immediate: true }) + beforeinstallprompt event — Install button appears automatically when browser detects installability" },
  { label: "Strength Calculator", desc: "calculateStrength() scores length (8+, 12+) and enabled options — returns Weak / Medium / Strong live as settings change" },
  { label: "Inline Confirm Toasts", desc: "react-hot-toast used as a modal replacement — delete and clear show Cancel + Confirm inside the toast itself" },
  { label: "Auto-generate on Change", desc: "generatePassword wrapped in useCallback, fires automatically via useEffect whenever length, char, or num changes" },
  { label: "History Cap", desc: "History sliced to last 10 entries on every generate — prevents unbounded localStorage growth" },
  { label: "Dark Mode", desc: "Theme component toggles .dark on <html>, Tailwind @custom-variant dark applies — no flash, no persistence bug (note: theme resets on refresh)" },
  {label:"Copy" , desc:"Copy password to Clipboard"},
  {label:"Localstorage" , desc:"Localstorage support"},
  { label: "Responsive Install Button", desc: "Two separate install buttons in Navbar — full pill button on sm+, icon-only circle on mobile" },
  { label: "Error Boundary", desc: "Wraps each route individually — Generator, History, Guide all isolated so one crash doesn't break the others" },
  { label: "404 Page", desc: "Wildcard route with Go Home + Go Back buttons, gradient 404 heading, glass card style matching app theme" },
],

errorFlows: [
  {
    title: "Both options unchecked",
    steps: [
      { text: "User unchecks Special and Numbers" },
      { text: "!char && !num check fires", type: "trigger" },
      { text: "generatePassword() sets currentPass to ''" },
      { text: "Empty password shown, no crash", type: "ok" },
    ],
  },
  {
    title: "Route render crash",
    steps: [
      { text: "PassGen / History / Guide throws during render" },
      { text: "Unexpected JS error fires", type: "trigger" },
      { text: "Per-route ErrorBoundary catches it" },
      { text: "'Something went wrong ⚠️' fallback shown", type: "ok" },
    ],
  },
  {
    title: "Unknown route",
    steps: [
      { text: "User visits /randompage" },
      { text: "No matching route found", type: "trigger" },
      { text: "Wildcard (*) route catches it" },
      { text: "404 page with Go Home / Go Back shown", type: "ok" },
    ],
  },
  {
    title: "PWA already installed",
    steps: [
      { text: "User installs the PWA" },
      { text: "appinstalled event fires", type: "trigger" },
      { text: "isInstallable set to false" },
      { text: "Install button removed from Navbar", type: "ok" },
    ],
  },
],
      github: "https://github.com/mayurpanchal-12/Password-Generator.git",
      live: "https://password-generator-three-ashen.vercel.app/",
      status: "Completed",
    },


  ];





  